import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  example: [{ type: 'autogenerated', dirName: 'example' }],
  element: [{ type: 'autogenerated', dirName: 'element' }],
  tutorial: [
    {
      type: 'category',
      collapsed: false,
      collapsible: false,
      label: '快速入门',
      items: ['tutorial/install', 'tutorial/draw_cube', 'tutorial/load_model'],
    },
    {
      type: 'category',
      collapsed: false,
      collapsible: false,
      label: '核心',
      items: ['tutorial/component'],
    },
  ],
};

export default sidebars;
